//  Takes country full names and return in ISO 3166 country code 2 digit format

export const convertCountry = {
  Bahrain: "BH",
  UK: "GB",
  UAE: "AE",
  Argentina: "AR",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Belgium: "BE",
  Brazil: "BR",
  USA: "US",
  Canada: "CA",
  China: "CN",
  Netherlands: "NL",
  Germany: "DE",
  Italy: "IT",
  Spain: "ES",
  France: "FR",
  Hungary: "HU",
  India: "IN",
  Japan: "JP",
  Korea: "KR",
  Malaysia: "MY",
  Mexico: "MX",
  Monaco: "MC",
  Morocco: "MA",
  Portugal: "PT",
  Qatar: "QA",
  Russia: "RU",
  "Saudi Arabia": "SA",
  Singapore: "SG",
  "South Africa": "ZA",
  Sweden: "SE",
  Switzerland: "CH",
  Turkey: "TR",
};
